version: '2'

services:
  app:
    image: transport-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: app
    depends_on:
      - db
      - mongodb
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_DATA_MONGODB_URI=mongodb://root:12345678@mongodb:27017/?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=admin
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=12345678
    networks:
      - transport-network

  db:
    image: 'postgres:14.0'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transport-network

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    networks:
      - transport-network

volumes:
  db-data:
  mongodb-data:

networks:
  transport-network:
    driver: bridge